language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
	- "pip install -q pync==1.4"
	- "python setup.py -q install"
# command to run tests
script: nosetests